server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service_likes
    username: root
    password: root21
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
        registerWithEureka: true
        fetchRegistry: true