eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

  client:
    prefer-same-zone: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-categories
          uri: lb://service-categories
          predicates:
            - Path=/api/categories/**
        - id: service-categories
          uri: lb://service-categories
          predicates:
            - Path=/api/subcategories/**
        - id: service-comments
          uri: lb://service-comments
          predicates:
            - Path=/api/comments/**
        - id: service-favorites
          uri: lb://service-favorites
          predicates:
            - Path=/api/favorites/**
        - id: service-files
          uri: lb://service-files
          predicates:
            - Path=/api/files/**
        - id: service-likes
          uri: lb://service-likes
          predicates:
            - Path=/api/likes/**
        - id: service-posts
          uri: lb://service-posts
          predicates:
            - Path=/api/posts/**
        - id: service-users
          uri: lb://service-users
          predicates:
            - Path=/api/users/**