server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/service_users
    username: postgres
    password: postgres21
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
       ddl-auto: update
       show-sql: true
       properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  name: eureka
  port: 8761
  preferSameZone: false
  shouldUseDns: false
  serviceUrl:
    default: http://localhost:8761/eureka/v2/
  shouldOnDemandUpdateStatusChange: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}