server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service_likes
    username: root
    password: root21
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  name: eureka
  port: 8761
  preferSameZone: false
  shouldUseDns: false
  serviceUrl:
    default: http://localhost:8761/eureka/v2/
  shouldOnDemandUpdateStatusChange: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}