eureka:
  name: eureka
  port: 8761
  preferSameZone: false
  shouldUseDns: false
  serviceUrl:
    default: http://localhost:8761/eureka/v2/
  shouldOnDemandUpdateStatusChange: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-categories
          uri: lb://service-categories
          predicates:
            - Path=/api/categories/**
        - id: service-categories
          uri: lb://service-categories
          predicates:
            - Path=/api/subcategories/**
        - id: service-comments
          uri: lb://service-comments
          predicates:
            - Path=/api/comments/**
        - id: service-favorites
          uri: lb://service-favorites
          predicates:
            - Path=/api/favorites/**
        - id: service-files
          uri: lb://service-files
          predicates:
            - Path=/api/files/**
        - id: service-likes
          uri: lb://service-likes
          predicates:
            - Path=/api/likes/**
        - id: service-posts
          uri: lb://service-posts
          predicates:
            - Path=/api/posts/**
        - id: service-users
          uri: lb://service-users
          predicates:
            - Path=/api/users/**