#MongoDB
server:
  port: 8086
spring:
  data:
    mongodb:
      uri: mongodb+srv://dh212:ypLJROgrdqhPiqRL@cluster0.c0o0skb.mongodb.net/?retryWrites=true&w=majority
      database: service-posts

eureka:
  name: eureka
  port: 8761
  preferSameZone: false
  shouldUseDns: false
  serviceUrl:
    default: http://localhost:8761/eureka/v2/
  shouldOnDemandUpdateStatusChange: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

